[package]
name = "todo-rust"
version = "0.1.0"
edition = "2024"


[dependencies]
time = { version = "0.3.44", features = ["serde"] }
uuid = { version = "1.19.0", features = ["v7", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
